language: python
python:
  - '2.7'
  - '3.4'
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  global:
  - TWILIO_ACCOUNT_SID=AC2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  - TWILIO_AUTH_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  - TWILIO_NUMBER=+15551230987
before_script:
  - python manage.py db upgrade
script:
  - coverage run manage.py test
after_script:
  - coverage report
